#docker-compose.yml
version: "3"
services:
  exporter:
    image: "bitnami/node-exporter"
    networks:
      - monitoring
    ports:
      - "9100:9100"
  graphana:
    image: grafana/grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
  prometheus:
    image: "bitnami/prometheus"
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/opt/bitnami/prometheus/data
      - ./configs/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
  forum:
    build: .
    networks:
      - monitoring
    ports:
      - "5000:5000"
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data:
  grafana_data:
