global:
  evaluation_interval: 10s
  scrape_interval: 10s
scrape_configs:
  - job_name: "system"
    static_configs:
      - targets: ["localhost:9090", "exporter:9100"]
  - job_name: "forum"
    static_configs:
      - targets: ["forum:8080"]
